
[server]
node_id = "nexus-node-1"
bind_address = "0.0.0.0:9090"
advertise_address = "127.0.0.1:9090"
data_dir = "./data"

[broker]
max_message_size = "1MB"
batch_size = 16384
batch_timeout_ms = 10
compression = "lz4"
enable_zero_copy = true

[storage]
segment_size = "1GB"
retention_hours = 168
compaction_threshold = 0.5
compression = "lz4"
encryption_enabled = false

[performance]
worker_threads = 4
max_connections = 1000
tcp_nodelay = true
tcp_keepalive = true
buffer_size = "64KB"

[monitoring]
metrics_enabled = true
metrics_port = 9091
tracing_enabled = true
log_level = "info"
